trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),

]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create_account'),
    path('update_account/', views.update_account_info, name='update_account_info'),
    path('account_status/', views.update_account_status, name='update_account_status'),
    path('activate_account', views.reactivate_account, name='reactivate_account'),
    path('pickup_day/', views.change_pickup_day, name='change_pickup_day'),

]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('update_account/', views.update, name="update"),
    path('upcoming_pickups/', views.upcoming_pickups, name='upcoming_pickups'),
    path('pickup_location/', views.pickup_location, name='pickup_location')
]

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Base{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
      html, body { height: 100%; width: 100%; background-color: #1668BE; color: white}
      svg { width: 60px; height: 40px; color: black; }
      a { color: white; }
      .nav-item,.nav-link {font-weight: bolder; color: black; }
      .nav-link:active {background-color:#1668BE;}
      .nav-link:hover {color:grey; font-weight: bold;}
      .navbar-toggler, .navbar-toggler-icon {color:black;}
      .customer__update__account > label {font-size: 1.25rem;padding-right: 5px;}
    </style>
</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <nav class="navbar navbar-expand-lg  bg-light customer">
  <a class="navbar-brand" href="{% url 'customers:index'  %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
  <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
</svg></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-subtract" viewBox="0 0 16 16">
  <path d="M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2z"/>
    </svg></span>

  </button>
  <div class="collapse navbar-collapse" id="navbarCustomer">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link " href="{% url 'customers:index' %}">Home</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'customers:update_account_info' %}">Update Account</a>
      </li>
      <li class="nav-item">
        {% if customer.account_status is False %}
        <a class="nav-link" href="{% url 'customers:reactivate_account' %}">Account Status</a>
        {% else %}
        <a class="nav-link" href="{% url 'customers:update_account_status' %}">Account Status</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% if customer.pickup_day == 'N/A' and customer.specific_date is None %}
        <a class="nav-link" href="{% url 'customers:change_pickup_day' %}">Start Service</a>
        {% elif customer.pickup_day != 'N/A' or customer.specific_date is not None %}
        <a class="nav-link" href="{% url 'customers:change_pickup_day' %}">Update Service</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>
    {% elif group.name == "Employees" %}
    <nav class="navbar navbar-expand-lg bg-light employee">
  <a class="navbar-brand" href="{% url 'employees:index'  %}"><svg xmlns="http://www.w3.org/2000/svg" width="13" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
  <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
</svg></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-menu-up" viewBox="0 0 16 16" style="position:relative;right:12px;bottom:5px;">
  <path d="M7.646 15.854a.5.5 0 0 0 .708 0L10.207 14H14a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3.793l1.853 1.854zM1 9V6h14v3H1zm14 1v2a1 1 0 0 1-1 1h-3.793a1 1 0 0 0-.707.293l-1.5 1.5-1.5-1.5A1 1 0 0 0 5.793 13H2a1 1 0 0 1-1-1v-2h14zm0-5H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v2zM2 11.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 0-1h-8a.5.5 0 0 0-.5.5zm0-4a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11a.5.5 0 0 0-.5.5zm0-4a.5.5 0 0 0 .5.5h6a.5.5 0 0 0 0-1h-6a.5.5 0 0 0-.5.5z"/>
</svg></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarEmployee">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'employees:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'employees:upcoming_pickups' %}">Upcoming Collections </a>
      </li>
    </ul>
  </div>
</nav>
{% endif %}
  {% endfor %}
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
{# This is the parent view that can be inherited by any other views #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Portal{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <div style="margin-left:2rem;">
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
    or
  <a href="{% url 'accounts:register' %}">Sign Up</a>
  </div>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}