trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),

]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('update_account/', views.update, name="update"),
    path('upcoming_pickups/', views.upcoming_pickups, name='upcoming_pickups'),
    path('pickup_location/', views.pickup_location, name='pickup_location')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories


class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', default=0, on_delete=models.CASCADE)
    zipcode = models.IntegerField(default=None)

trash_collector/employees/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from .models import Employee
from django import forms
from django.apps import apps
from datetime import date, timedelta
import calendar
from django.forms import ModelForm


# Create your views here.

class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'zipcode']
        labels = {
            'name': 'Name',
            'zipcode': 'Zip Code'
        }


class EmployeeDateSelectionForm(forms.Form):
    today = date.today()
    end_date = today + timedelta(days=6)
    date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        widget=forms.widgets.DateInput(attrs={'type': 'date', 'min': today, 'max': end_date}),
        label='')


def index(request):
    user = request.user
    try:
        employee = Employee.objects.get(user=user.id)
    except:
        return render(request, 'employees/update_account.html')
    if employee:
        Customer = apps.get_model('customers.Customer')
        customers = Customer.objects.all()
        customer_list = []
        today = day_name()
        addresses = []
        today_date = date.today()

        context = {
            'customers': customer_list,
            'employee': employee,
            'addresses': addresses
        }

        for customer in customers:
            if customer.account_status is True and customer.pickup_day == today or customer.account_status is True and customer.specific_date == today_date:
                customer_list.append(customer)

        for customer in customer_list:
            if customer.zipcode != employee.zipcode:
                customer_list.remove(customer)
            address = customer.street.replace(' ', '+')
            addresses.append(address)


        if request.method == 'POST' and 'confirm_pickup' in request.POST:
            for customer in customer_list:
                if customer.pickup_day == today:
                    customer.amount_due += 7
                if customer.specific_date == today_date:
                    customer.amount_due += 50
                customer.is_collected = True
                customer.save()

        return render(request, 'employees/index.html', context)


def update(request):
    user = request.user
    if request.method == 'POST':
        name = request.POST.get('name')
        zipcode = request.POST.get('zipcode')
        new_employee = Employee(name=name, user=user, zipcode=zipcode)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/update_account.html')


def day_name():
    today_day = date.today()
    today_day = calendar.day_name[today_day.weekday()]
    return today_day


def upcoming_pickups(request):
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    user = request.user
    employee = Employee.objects.get(user=user.id)
    form = EmployeeDateSelectionForm(request.POST or None)



    context_main = {
        'employee': employee,
        'customers': customers,
        'form': form
    }

    if form.is_valid():
        selected_date = form.cleaned_data.get('date')
        selected_day_name = selected_date.strftime('%A')

        for customer in customers:
            if customer.zipcode == employee.zipcode and customer.account_status is True:
                filtered_date = customers.filter(specific_date=selected_date)
                filtered_day = customers.filter(pickup_day=selected_day_name)
                filtered = filtered_date | filtered_day
                context = {
                    'customers': filtered,
                    'form': form
                }
                return render(request, 'employees/upcoming_pickups.html', context)

    return render(request, 'employees/upcoming_pickups.html', context_main)


def pickup_location(request):
    pass

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}
{%load static%}

{% block title %}Employee Home{% endblock %}

{% block content %}
<div class="container-fluid header">
  {% if user.is_authenticated %}
  {% if not employee %}
  <h1 style="padding-left: 10%; margin-top: 5%;">Hello {{user.id}}!</h1>
  {% else %}
  <h1 style="padding-left: 10%; margin-top: 5%;">Hello {{employee.name}}!</h1>
  {% endif %}
</div>
<div class="container-fluid">
<div class="row no-gutters justify-content-center align-items-center customer__table">
  <table class="col-4" style="width: 35%; text-align:center; line-height: 2.5rem; ">
    <tr style="font-size: 1.25rem">
      <th>Customers</th>
      <th>Address</th>
    </tr>
    {% for customer in customers %}
    <tr style="font-size: 1.15rem">
      <td>&nbsp;{{customer.name}}</td>
      <td style="margin-left: 2%;">&nbsp;{{customer.street}} / {{customer.zipcode}} / {{customer.city}}</td>
    </tr>
    {% endfor %}
  </table>

{% for customer in customers %}
{% if customer.is_collected == False and forloop.first %}
  <form class="col" action="{% url 'employees:index' %}" method='POST'>
      {% csrf_token %}
    <button class="btn btn-dark" name="confirm_pickup" id="confirm_pickup" type="submit"
          style="cursor: pointer;margin-left:3rem;position:relative;top:13.5rem;right:30rem;">Route Completed</button>
  </form>
{% else %}
{% endif %}
{% endfor %}
<div class="col-5 justify-content-start">
<img src="https://maps.googleapis.com/maps/api/staticmap?center=99504&zoom=13&scale=1&size
=600x500&maptype=hybrid&key=AIzaSyCbrvdmLudcLIt5j52ZZSwfCMyNkU9itqo&format=png&visual_refresh
=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:1%7C{{addresses.0}},Anchorage&markers
=size:mid%7Ccolor:0xff0000%7Clabel:2%7C{{addresses.1}},Anchorage&markers=size:mid%7Ccolor:0xff0000%7Clabel:3%7C{{addresses.2}},+Anchorage"  >
</div>
<div class="col-8" style="position:relative;bottom: 3.5rem;">
  <button type="button" class="btn btn-dark" style="position:relative;left:10rem;"><a href="{% url 'logout' %}" style="color:white;">Log Out</a></button>
</div>

</div>

</div>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/pickup_location.html
{% extends 'base.html' %}

{% block title %}{% block header %} Upcoming Pickups {% endblock %}{% endblock %}

{% block content %}
<table>
  <tr>
    <th>Customers</th>
    <th>Address</th>
  </tr>
  {% for customer in customers %}
  <tr>
    <td>{{customer.name}}</td>
    <td>{{customer.street}}/{{customer.zipcode}}/{{customer.city}}</td>
  </tr>
  {% endfor %}
</table>


<img src="https://maps.googleapis.com/maps/api/staticmap?size=512x512&zoom=12&center=Chicago&format=png&style=feature:road.highway%7Celement:geometry%7Cvisibility:simplified%7Ccolor:0xc280e9&style=feature:transit.line%7Cvisibility:simplified%7Ccolor:0xbababa&style=feature:road.highway%7Celement:labels.text.stroke%7Cvisibility:on%7Ccolor:
0xb06eba&style=feature:road.highway%7Celement:labels.text.fill%7Cvisibility:on%7Ccolor:0xffffff&key=AIzaSyCbrvdmLudcLIt5j52ZZSwfCMyNkU9itqo"  >
  {% endblock %}

trash_collector/employees/templates/employees/upcoming_pickups.html
{% extends 'base.html' %}

{% block title %}Upcoming Pickups{% endblock %}{% block header %}
<div class="container-fluid">
  <h1 class="row no-gutters justify-content-center" style="margin-top:3%;margin-bottom:7%;">Upcoming Collections</h1>
</div>

{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center no-gutters" style="font-size:  1.2rem">
  <form action="{% url 'employees:upcoming_pickups' %}" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <span>{{ form.as_table }}</span>
  <button class="btn btn-dark" type="submit" value="Submit" style="position:relative;bottom:2.5px;">Submit</button>
  </form>
    </div>
  <div class="row no-gutters justify-content-center">
  <table class="table table-sm" style="margin-top: 7%;width: 50%;text-align: center; background-color: black;">
    <tr style="font-size: 1.7rem;">
      <th>Customers</th>
      <th>Address</th>
    </tr>
    {% for customer in customers %}
    <tr>
      <td>{{customer.name}}</td>
      <td>{{customer.street}} / {{customer.zipcode}} / {{customer.city}}</td>
    </tr>
    {% endfor %}
  </table>
    </div>

</div>
  {% endblock %}

trash_collector/employees/templates/employees/update_account.html
{% extends 'base.html' %}

{% block title %} Update Account Info{% endblock %}
{% block header %}
<div class="contiainer-fluid">
    <h1 class="row no-gutters justify-content-center" style="margin-top:3%;">Update Account Info</h1>
</div>
 {% endblock %}
{% block content %}
<div class="container-fluid">
    <form style="margin-top:3%;" class="row no-gutters justify-content-center" action="{% url 'employees:update' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label style="font-size:1.15rem;margin-right:5px;">Name:</label><input type="text" name="name" id="name" style="height: 5%;"><br>
    <label style="font-size:1.15rem;margin-left:2%;margin-right:5px;">Zip Code: </label><input type="text" name="zipcode" id="zipcode" style="height: 5.5%;"><br>
    <input type="submit" value="Submit" style="margin-left:9px;position:relative;bottom:2px;height:5%;background-color:#343A40;color:white;">
    </form>
</div>
<div class="container-fluid">
    <div class="row no-gutters justify-content-center">
    </div>
</div>
{% endblock %}