trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),

]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create_account'),
    path('update_account/', views.update_account_info, name='update_account_info'),
    path('account_status/', views.update_account_status, name='update_account_status'),
    path('activate_account', views.reactivate_account, name='reactivate_account'),
    path('pickup_day/', views.change_pickup_day, name='change_pickup_day'),

]

trash_collector/customers/models.py
from django.db import models


# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories

class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', default=0, on_delete=models.CASCADE)
    street = models.CharField(max_length=50, default=None)
    city = models.CharField(max_length=50, default=None)
    zipcode = models.IntegerField(default=None)
    account_status = models.BooleanField(default=True)
    suspend_start = models.DateField(null=True, blank=True)
    suspend_end = models.DateField(null=True, blank=True)
    pickup_day = models.CharField(max_length=50, blank=True)
    specific_date = models.DateField(null=True, blank=True)
    projected_total = models.DecimalField(max_digits=5, decimal_places=2, blank=True, default=0)
    amount_due = models.DecimalField(max_digits=5, decimal_places=2, blank=True, default=0)
    is_collected = models.BooleanField(default=False)

    def __str__(self):
        return self.name

trash_collector/customers/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, reverse, get_object_or_404, redirect
from .models import Customer
from django import forms
from datetime import datetime,date,timedelta
from django.forms import ModelForm, SelectDateWidget
from datetime import date


# Create your views here.


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'user', 'street', 'city', 'zipcode', 'specific_date', 'pickup_day', 'user',
                  'account_status', 'suspend_start', 'suspend_end']
        labels = {
            'name': 'Name',
            'street': 'Street Address',
            'city': 'City',
            'zipcode': 'Zip Code',
            'suspend_end': 'Suspend End',
            'suspend_start': 'Suspend Start'

        }
        widgets = {
            'suspend_start': SelectDateWidget(years=range(2021, 2021)),
            'suspend_end': SelectDateWidget(years=range(2021, 2021))
        }


class CustomerSuspendForm(forms.Form):
    today = date.today()
    max_date = today + timedelta(days=90)
    start_date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        widget=forms.widgets.DateInput(attrs={'type': 'date', 'min': today, 'max': max_date}),
        label='Start Date')
    end_date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        widget=forms.widgets.DateInput(attrs={'type': 'date', 'min': today, 'max': max_date}),
        label=' End Date ')


def index(request):
    # get the logged in user within any view function
    user = request.user
    try:
        customer = Customer.objects.get(user=user.id)
        context = {
            'customer': customer
        }
        return render(request, 'customers/index.html', context)

    except:
        context_user = {
            'user': user
        }
        return render(request, 'customers/create.html', context_user)


def create(request):
    user = request.user
    if request.method == 'POST':
        name = request.POST.get('name')
        street = request.POST.get('street')
        city = request.POST.get('city')
        zipcode = request.POST.get('zipcode')
        new_customer = Customer(name=name, user=user, street=street, city=city, zipcode=zipcode,
                                account_status=True, pickup_day='N/A')
        new_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/create.html')


def update_account_info(request):
    user = request.user
    customer = get_object_or_404(Customer, user_id=user.pk)
    form = CustomerForm(request.POST or None, instance=customer)
    form.fields.pop('specific_date')
    form.fields.pop('user')
    form.fields.pop('account_status')
    form.fields.pop('pickup_day')
    form.fields.pop('suspend_start')
    form.fields.pop('suspend_end')
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('customers:index'))
    context ={
        'form': form,
        'customer': customer
    }
    return render(request, 'customers/update_account.html', context)


def update_account_status(request):
    today_date = date.today()
    user = request.user
    customer = Customer.objects.get(user=user.id)
    form = CustomerSuspendForm(request.POST or None)

    context_main = {
        'customer': customer,
        'form': form
    }

    if form.is_valid():
        customer.suspend_start = form.cleaned_data.get('start_date')
        customer.suspend_end = form.cleaned_data.get('end_date')
        if customer.suspend_start <= today_date <= customer.suspend_end:
            customer.account_status = False
            customer.save()
            return redirect('customers:index')
        else:
            customer.account_status = True
            customer.save()
            return redirect('customers:index')

    return render(request, 'customers/account_status.html', context_main)


#Might be able to insert entire function into update account status function

def reactivate_account(request):
    print('Activate!!!')
    user = request.user
    customer = get_object_or_404(Customer, user_id=user.pk)

    context = {
        'customer': customer
    }

    if request.method == 'POST' and 'activate' in request.POST:
        customer.account_status = True
        customer.suspend_start = None
        customer.suspend_end = None
        customer.save()
        return redirect('customers:index')
    else:
        return render(request, 'customers/activate_account.html', context)


def change_pickup_day(request):
    user = request.user
    customer = get_object_or_404(Customer, user_id=user.pk)
    context = {
        'customer': customer,
    }
    days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
    if request.method == 'POST':
        customer.pickup_day = request.POST.get('pickup_day')
        customer.specific_date = request.POST.get('specific_date')

        #If not pickup date is selected value will equal 'N/A'
        value = 'N/A'

        if customer.specific_date == '':
            customer.specific_date = None
            if customer.pickup_day == value:
                customer.projected_total = 0
            elif customer.pickup_day in days_of_week:
                customer.projected_total = 28
            customer.save()
        else:
            if customer.pickup_day == value:
                customer.projected_total = 50

            elif customer.pickup_day in days_of_week:
                customer.projected_total = 78

            customer.save()

        return HttpResponseRedirect(reverse('customers:index'), context)
    else:
        return render(request, 'customers/pickup_day.html', context)

trash_collector/customers/templates/customers/account_status.html
{% extends 'base.html' %}

{% block title %}Account Status{% endblock %}
{% block header %}
<div class="container-fluid">
<h1 class="row no-gutters justify-content-center" style="margin-top: 3%;font-size: 4rem;">Account Status</h1>
</div>
{% endblock %}{
{% block content %}
<div class="container-fluid">
        <div class="row no-gutters justify-content-center" style="margin-top:1.5%">
            {% if customer.account_status is True %}
            <h3>Current Status: Active</h3><br>
            {% else %}
            <h3>Current Status: Suspended</h3><br>
            {% endif %}
        </div>
        <div class="row no-gutters justify-content-center" style="margin-top:1.5%;">
            <form  class="customer__account__status" action="{% url 'customers:update_account_status' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark" style="position:relative;left:2rem;margin-top:5%;" >Update Account Status</button>
            </form>
        </div>
</div>
{% endblock %}

trash_collector/customers/templates/customers/activate_account.html
{% extends 'base.html' %}

{% block title %}{% block header %} Activate Account {% endblock %}{% endblock %}

{% block content %}
    {% if customer.account_status is True %}
    <span>Account is currently active!</span><br>
    {% else %}
    <span>Account Status: Suspended</span><br>
    {% endif %}
    {% if customer.account_status is False %}
    <form action="{% url 'customers:reactivate_account' %}" method='POST'>
        {% csrf_token %}
    <button class="btn btn-dark" name="activate" type="submit" value="Activate">Re-Activate Account</button>
    </form>
    {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/create.html
{% extends 'base.html' %}

{% block title %}Customer Home {% endblock %}

{% block content %}
<div class="container-fluid">
    <h1 class="row no-gutters justify-content-center" style="margin-top:3%;margin-bottom:5%;">Create Account</h1>
</div>
<div class="container-fluid">
     <div class="row no-gutters justify-content-center">
        <form action="{% url 'customers:create_account' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <label style="margin-right:10px;">Name:</label><input type="text" name="name" id="name"><br>
        <label style="margin-right:10px;">Street:</label><input type="text" name="street" id="street"><br>
        <label style="margin-right:25px;">City:</label><input type="text" name="city" id="city"><br>
        <label style="margin-right:10px;position:relative;right:22px;">Zip Code:</label>
            <input style="margin-left:-25px;" type="text" name="zipcode" id="zipcode"><br>
        <input style="margin-top:2%;position:relative;left:7rem;background-color:#343A40;color:white;" type="submit" value="Create" />
        </form>
    </div>
</div>
{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}

{% block title %}
Customer Home
{% endblock %}
{% block content %}
  {% if user.is_authenticated%}
  {% if not customer %}
  <div class="container-fluid" style="line-height: 2.5rem;">
    <h1 class="row justify-content-center no-gutters">Hello {{user.username}}!</h1>
    {%else%}
    <h1 class="row justify-content-center no-gutters" style="padding-top: 2rem;">Hello {{customer.name}}!</h1>
  </div>
  <div class="container-fluid" style="line-height: 3rem;">
    <h3 class="row justify-content-center no-gutters" style="font-size: 2rem; padding-bottom: 2rem; padding-top: 2rem;">Account Details</h3>
    <div class="row main__content justify-content-center no-gutters" style="font-size: 1.25rem;margin-left:2.5%;">
      <table>
        <tr>
          {% if customer.account_status is True %}
          <th>Account Status:  </th>
          <td>&nbsp;Active</td>
        </tr>
          {% else %}
        <tr>
          <th>Account Status:  </th>
          <td>&nbsp;Suspended</td>
        </tr>
        {% endif %}
        <tr>
          <th>Address:</th>
          <td>&nbsp;{{customer.street}} / {{customer.zipcode}}</td>
        </tr>
        <tr>
          {% if customer.pickup_day != 'N/A' %}
          <th>Pickup Day:</th><td>&nbsp;{{customer.pickup_day}}</td>
          {% else %}
          <th>Pickup Day:</th><td>&nbsp;Not Selected</td>
          {% endif %}
        </tr>
        {% if customer.specific_date is not None %}
        <tr>
          <th>One-Time Pickup:</th><td>&nbsp;{{customer.specific_date}}</td>
        </tr>
        {% else %}
        {% endif %}
        <tr>
          <th>Projected Total:</th><td>&nbsp;${{customer.projected_total}}</td>
        </tr>
        <tr>
          <th>Amount Due:</th><td>&nbsp;${{customer.amount_due}}</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="container-fluid" style="margin-top:7%;">
    <div class="content row no-gutters justify-content-center" >
      <button type="button" class="btn btn-dark">
        <a href="{% url 'logout' %}">Log Out</a>
      </button>
    </div>
  </div>

{% endif%}
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
  {% if not customer%}
    <a href="{% url 'customers:create_account' %}" >
    <button class="btn btn-dark" type="button">Start your service today!</button>
    </a>
<a href="{% url 'logout' %}"><button type="button" class="btn btn-dark" >Log Out</button></a>

  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/pickup_day.html
{% extends 'base.html' %}

{% block title %} Start Service | Update Service {% endblock %}


{% block content %}
<div class="container-fluid">
    <h1 class="row no-gutter justify-content-center">Services</h1>
</div>
<div class="container-fluid">
    <div class="row no-gutters justify-content-center" style="margin-top:2rem;margin-bottom:3rem;">
        <table class="table table-sm" style="width:50%;text-align:center;">
            <tr>
                <th>Rates</th>
                <td>Monthly</td>
                <td>One-Time</td>
            </tr>
            <tr>
                <td></td>
                <td>$28</td>
                <td> $50 </td>
            </tr>
        </table>
        </div>
 </div>
<div class="row no-gutters justify-content-center">
<form action="{% url 'customers:change_pickup_day' %}" method="post">
    {% csrf_token %}
    <label for="pickup_day" style="font-size:1.25rem;">Pickup Day: </label>
    <select name="pickup_day" id="pickup_day" style="height:90%;width:130px;margin-right:9px;cursor:pointer;">
        <option value="N/A"></option>
        <option value="Monday">Monday</option>
        <option value="Tuesday">Tuesday</option>
        <option value="Wednesday">Wednesday</option>
        <option value="Thursday">Thursday</option>
        <option value="Friday">Friday</option>
    </select>
    <label style="font-size:1.25rem;margin-right:5px;">One-Time Pickup:</label>
    <input style="height:90%;width:13.7rem;cursor:pointer;" type="date" name="specific_date" id="specific_date" min="2021-01-01" max="2021-12-31">
    <button class="btn btn-dark" type="submit" style="height:90%;position:relative;bottom:.10rem;left:1.5rem;">
        <span style="vertical-align:start;">Submit</span>
    </button>
  </form>
</div>
{% endblock %}

trash_collector/customers/templates/customers/update_account.html
{% extends 'base.html' %}

{% block title %}Update Account Info{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1 class="row no-gutters justify-content-center">Update Account</h1>
</div>
<div class="container-fluid">
    <div class="row no-gutters justify-content-center" style="margin-top: 7%;">
<form class="customer__update__account"  action="{% url 'customers:update_account_info' %}" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" class="btn btn-dark" style="color:white;position:relative;bottom:2.5px;">Update Account Information</button>
  </form>
    </div>
</div>
{% endblock %}